name: Keep-Alive Bot

on:
  schedule:
    # Roda a cada 10 minutos
    - cron: '*/5 * * * *'

jobs:
  ping-my-sites: # Mudei o nome do job para o plural, para ficar mais claro
    runs-on: ubuntu-latest
    steps:
      - name: Ping Agendamento Online
        run: curl -sS https://agendamentos-barbearia-lucas-borges.onrender.com > /dev/null

      # ----- ADIÇÃO NOVA -----
      - name: Ping Controle Diario
        run: curl -sS https://controle-diario-barbearia-lucas-borges.onrender.com/ > /dev/null

      # ----- ADIÇÃO NOVA -----
      - name: Ping Agendamento Interno
        run: curl -sS https://agendamento-interno-barbearia-lucas.onrender.com > /dev/null
        #vai funcionar

      - name: Ping Dashboard Interno
        run: curl -sS https://dashboard-barbearia-lb.onrender.com > /dev/null
     
      - name: Ping Regtistro Diário
        run: curl -sS https://registro-barbearia-lucas-borges.onrender.com > /dev/null
